"""
Correction artifact produced by the Code Corrector agent.
"""

from uuid import UUID

from typing import Optional
from pydantic import Field, computed_field

from schemas.artifacts import SourceCodeArtifact
from schemas.base import ArtifactBase
from schemas.enums import ArtifactType, CreatorType


class CorrectedCodeArtifact(ArtifactBase):
    """
    Artifact representing the corrected source code generated by the
    Code Corrector agent.
    """

    artifact_type: ArtifactType = ArtifactType.CORRECTED_CODE

    origin: CreatorType = CreatorType.CORRECTOR

    corrected_source: SourceCodeArtifact = Field(
        description="Corrected source code artifact."
    )

    modification_summary: Optional[str] = Field(
        default=None,
        description="Summary of modifications made during correction.",
    )

    correction_notes: Optional[str] = Field(
        default=None,
        description="Additional notes from the corrector.",
    )

    fixed_issue_ids: list[UUID] = Field(
        default_factory=list,
        description="Identifiers of issues addressed during correction.",
    )

    correction_confidence: float = Field(
        default=1.0,
        ge=0.0,
        le=1.0,
        description="Overall confidence in the correction.",
    )

    @computed_field
    @property
    def fixed_issue_count(self) -> int:
        """Number of issues addressed during correction."""
        return len(self.fixed_issue_ids)